# SPDX-License-Identifier: MIT OR Apache-2.0
[contract]

[wasm-opt]
flags = ["-O3", "--one-caller-inline-max-function-size=1000", "--enable-bulk-memory-opt", "--enable-sign-ext", "--enable-mutable-globals", "--enable-nontrapping-float-to-int"]
