# SPDX-License-Identifier: MIT OR Apache-2.0
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "forge-std/=lib/forge-std/src/",
]
solc_version = "0.8.37"
evm_version = "osaka"
optimizer = true
optimizer_runs = 200
isolate = true
fs_permissions = [
    { access = "read-write", path = "../deployments" },
    { access = "read-write", path = "../stylus/target" },
    { access = "read", path = "../stylus/contracts/margin/testdata" },
    { access = "read", path = "../stylus/contracts/margin/parameters.json" },
    { access = "read", path = "../stylus/contracts/band/testdata" },
    { access = "read", path = "./test/data" },
]

[rpc_endpoints]
robinhood = "${ROBINHOOD_RPC_URL}"
robinhood-testnet = "${ROBINHOOD_TESTNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
devnode = "http://127.0.0.1:8547"
robinhood-logs = "${ROBINHOOD_LOGS_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
